Repository paritytech/shasper, pull requests merged in 2018-11, with the labels that each got.

#17 Add a leading /** to /target in .gitignore
  .gitignore
Labels: A2-insubstantial 👶, M2-config 📂

#16 Remove unused macro_use with alloc import in ssz-derive
  util/ssz-derive/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#12 Installation: git clone, bash
  README.md
Labels: A8-looksgood 🦄, M3-docs 📑

#28 Update substrate deps to git HEAD
  Cargo.lock
  network/src/lib.rs
  runtime/Cargo.toml
  runtime/src/attestation.rs
  runtime/src/extrinsic.rs
  runtime/src/lib.rs
  runtime/src/spec/mod.rs
  runtime/src/state.rs
  runtime/src/system.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  transaction-pool/src/lib.rs
  util/ssz-hash-derive/tests/mod.rs
  util/ssz-hash/src/lib.rs
  util/ssz/src/codec.rs
Labels: A0-pleasereview 🤓
