Repository paritytech/shasper, pull requests merged in 2018-10, with the labels that each got.

#3 Setup Travis CI for shasper repo
  .travis.yml
  README.md
  runtime/src/spec/mod.rs
  scripts/build.sh
  scripts/ci.sh
  scripts/common.sh
  scripts/init.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#5 Initial .gitlab-ci.yml build file
  .gitlab-ci.yml
Labels: A6-mustntgrumble 💦, M1-ci 🙉

#6 Remove Travis CI
  .travis.yml
  README.md
Labels: A0-pleasereview 🤓, M1-ci 🙉
