Repository paritytech/shasper, pull requests merged in 2019-02, with the labels that each got.

#49 README: add install clang req.
  README.md
Labels: A2-insubstantial 👶, M3-docs 📑

#50 Generic Casper FFG finalization and justification
  Cargo.lock
  casper/Cargo.toml
  casper/src/casper.rs
  casper/src/lib.rs
Labels: A0-pleasereview 🤓

#51 Split casper function and data and add tests
  casper/src/casper.rs
Labels: A0-pleasereview 🤓

#52 Casper and beacon rewards and penalities
  casper/src/casper.rs
  casper/src/lib.rs
  casper/src/reward.rs
Labels: A0-pleasereview 🤓

#53 Refactor casper and rewards mod
  casper/src/casper.rs
  casper/src/lib.rs
  casper/src/reward.rs
  casper/src/store.rs
Labels: A0-pleasereview 🤓

#54 Add default reward schemes
  casper/src/casper.rs
  casper/src/reward.rs
  casper/src/store.rs
Labels: A0-pleasereview 🤓

#55 Refactor and make reward conditions cleaner
  casper/src/casper.rs
  casper/src/reward.rs
  casper/src/store.rs
Labels: A0-pleasereview 🤓

#56 Reward should use active validators of previous epoch
  casper/src/reward.rs
Labels: A2-insubstantial 👶

#57 Add default scheme for penalty/slashings
  casper/src/reward.rs
Labels: A0-pleasereview 🤓

#58 Integrate geneirc casper logic and rewards to runtime
  Cargo.lock
  casper/Cargo.toml
  casper/src/casper.rs
  casper/src/lib.rs
  casper/src/reward.rs
  casper/src/store.rs
  consensus/Cargo.toml
  consensus/primitives/src/lib.rs
  consensus/src/block_import.rs
  consensus/src/lib.rs
  primitives/Cargo.toml
  primitives/src/attestation.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/consts.rs
  runtime/src/extrinsic.rs
  runtime/src/genesis.rs
  runtime/src/lib.rs
  runtime/src/spec.rs
  runtime/src/state.rs
  runtime/src/storage.rs
  runtime/src/utils.rs
  runtime/src/validation.rs
  runtime/src/validators.rs
  runtime/wasm/Cargo.lock
  src/chain_spec.rs
  src/main.rs
  util/ssz-hash-derive/Cargo.toml
  util/ssz-hash/Cargo.toml
Labels: A0-pleasereview 🤓

#59 shasper: fix binary name
  Cargo.toml
  primitives/src/lib.rs
Labels: A2-insubstantial 👶, M0-build 🏗

#60 Submit attestations to transaction pool for every epoch if validator is specified
  casper/src/casper.rs
  consensus/primitives/src/lib.rs
  consensus/src/lib.rs
  primitives/src/attestation.rs
  primitives/src/lib.rs
  runtime/src/consts.rs
  runtime/src/lib.rs
  runtime/src/state.rs
  runtime/src/storage.rs
  src/service.rs
Labels: A0-pleasereview 🤓

#64 Fix attestation not being included in pending
  casper/src/reward.rs
  consensus/src/block_import.rs
  runtime/src/lib.rs
Labels: A0-pleasereview 🤓

#66 Fix the issue that multiple attestations got into multiple blocks
  runtime/src/lib.rs
Labels: A0-pleasereview 🤓

#69 Write finalization info into backend
  consensus/src/block_import.rs
  src/service.rs
Labels: A0-pleasereview 🤓

#70 Upgrade to substrate HEAD
  Cargo.lock
  runtime/src/genesis.rs
  runtime/wasm/Cargo.lock
Labels: A0-pleasereview 🤓

#71 Add a short-lived public testnet
  consensus/src/lib.rs
  src/chain_spec.rs
Labels: A0-pleasereview 🤓

#72 Update substrate HEAD
  Cargo.lock
  consensus/src/lib.rs
  runtime/wasm/Cargo.lock
  src/service.rs
Labels: A0-pleasereview 🤓

#73 Commit wasm binary files
  README.md
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
Labels: A0-pleasereview 🤓

#75 Make the runtime native-only
  Cargo.lock
  Cargo.toml
  src/cli.rs
Labels: A0-pleasereview 🤓

#76 Fix finalization warning
  consensus/src/block_import.rs
Labels: A0-pleasereview 🤓

#77 Add aggregation support for attestation
  Cargo.lock
  consensus/src/lib.rs
  primitives/src/attestation.rs
  runtime/src/lib.rs
  runtime/src/state.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
Labels: A0-pleasereview 🤓

#78 Update Substrate HEAD
  Cargo.lock
  runtime/wasm/Cargo.lock
Labels: A0-pleasereview 🤓

#79 Allow setting custom keys via cli params
  README.md
  src/cli.rs
  src/cli.yml
  src/service.rs
Labels: A0-pleasereview 🤓

#80 Use real slot number
  consensus/src/block_import.rs
  consensus/src/lib.rs
  primitives/src/lib.rs
  runtime/src/consts.rs
  runtime/src/extrinsic.rs
  runtime/src/genesis.rs
  runtime/src/lib.rs
  runtime/src/storage.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
  src/chain_spec.rs
Labels: A0-pleasereview 🤓

#81 Fix attestation generation panic and refactor find_slot_header
  consensus/src/block_import.rs
  consensus/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview 🤓

#82 Always insert correct slot directly to genesis and fix slot calculation
  casper/src/casper.rs
  consensus/src/lib.rs
  runtime/src/genesis.rs
  runtime/src/lib.rs
  runtime/src/state.rs
  runtime/src/storage.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
Labels: A0-pleasereview 🤓

#83 Warn missing docs for runtime and refactor
  runtime/src/digest.rs
  runtime/src/extrinsic.rs
  runtime/src/genesis.rs
  runtime/src/lib.rs
  runtime/src/storage.rs
  runtime/src/utils.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
  src/service.rs
Labels: A0-pleasereview 🤓

#85 Introduce context trait to casper and refactor to use new interface
  casper/src/casper.rs
  casper/src/context.rs
  casper/src/lib.rs
  casper/src/reward.rs
  casper/src/store.rs
  consensus/src/lib.rs
  primitives/src/attestation.rs
  primitives/src/lib.rs
  runtime/src/genesis.rs
  runtime/src/state.rs
  runtime/src/storage.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/shasper_runtime.wasm
Labels: A0-pleasereview 🤓
