Repository paritytech/shasper, pull requests merged in 2019-12, with the labels that each got.

#192 Fix pubsub names
  blockchain/network/messages/src/lib.rs
Labels: A0-pleasereview 🤓

#193 CI optimizations
  .gitlab-ci.yml
Labels: M1-ci 🙉

#194 Clean up some unused imports
  blockchain/network/src/handler.rs
  blockchain/network/src/service.rs
  blockchain/src/main.rs
Labels: A2-insubstantial 👶
