Repository paritytech/shasper, pull requests merged in 2019-05, with the labels that each got.

#127 Update CI
  .gitlab-ci.yml
Labels: M1-ci 🙉

#130 Blockchain client built on libp2p and simple primitives
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/lmd-ghost/src/archive.rs
  blockchain/lmd-ghost/src/lib.rs
  blockchain/lmd-ghost/src/pruning.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#131 Properly use lmd-ghost fork choice for blockchain interface
  Cargo.lock
  beacon/src/executive/mod.rs
  blockchain/Cargo.toml
  blockchain/lmd-ghost/src/archive.rs
  blockchain/lmd-ghost/src/lib.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#132 Make config an input to executor
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#133 Add logic to push valid deposits to genesis block
  beacon/src/config.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#134 Implement basic block authoring logic for v0.7 spec
  beacon/src/config.rs
  beacon/src/error.rs
  beacon/src/executive/mod.rs
  beacon/src/executive/transition/per_epoch/registry.rs
  beacon/src/types/block.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#136 Propose block using real bls schemes
  Cargo.lock
  beacon/src/config.rs
  beacon/src/executive/helpers/mod.rs
  beacon/src/executive/mod.rs
  beacon/src/utils.rs
  blockchain/Cargo.toml
  blockchain/lmd-ghost/src/archive.rs
  blockchain/lmd-ghost/src/lib.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#137 Basic validator implementation
  beacon/src/executive/assignment.rs
  beacon/src/executive/choice.rs
  beacon/src/executive/helpers/mod.rs
  beacon/src/executive/mod.rs
  beacon/src/primitives/bitfield.rs
  beacon/src/types/state.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓

#138 show rust version
  .gitlab-ci.yml
Labels: A8-backport 🕸, M1-ci 🙉

#140 transaction-pool: aggregate signatures when attestation data is the same
  Cargo.lock
  beacon/src/config.rs
  beacon/src/primitives/bitfield.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
  blockchain/src/pool.rs
  crypto/src/lib.rs
Labels: A0-pleasereview 🤓

#141 RocksDB backend
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/lmd-ghost/Cargo.toml
  blockchain/lmd-ghost/src/archive.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
  blockchain/src/rocksdb.rs
Labels: A0-pleasereview 🤓

#142 Remove ImportAction::swap
  Cargo.lock
  blockchain/lmd-ghost/src/archive.rs
Labels: A0-pleasereview 🤓

#143 Overhaul backend interface design
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/lmd-ghost/Cargo.toml
  blockchain/lmd-ghost/src/archive.rs
  blockchain/src/backend.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
  blockchain/src/rocksdb.rs
Labels: A0-pleasereview 🤓

#151 Separate import lock from backend
  Cargo.lock
  blockchain/lmd-ghost/src/archive.rs
  blockchain/src/main.rs
Labels: A0-pleasereview 🤓, M4-lib-blockchain ⛓
